### ISSUE TITLE
Error In Pharo 7 Installing via Baseline

### ISSUE THREAD

**Issue by darth-cheney** [zweidenker/OpenAPI#19] opened 2019-10-05 21:56 UTC
When I run:
```smalltalk
Metacello new
    baseline: 'OpenAPI';
    repository: 'github://zweidenker/OpenAPI/';
    load.
```
I am getting what appears to be an Ombu error:
```
ZnBufferedReadWriteStream(Object)>>doesNotUnderstand: #defaultBufferSize
ZnBufferedReadWriteStream>>on:
ZnBufferedReadWriteStream class>>on:
FileReference>>binaryReadWriteStream
[ | initialPosition initialLocalName fileStream |
self entryBuffer isEmpty
	ifTrue: [ ^ self ].
fileStream := ZnCharacterReadWriteStream
	on: fileReference binaryReadWriteStream
	encoding: #utf8.
[ | anEntryWriter |
fileStream setToEnd.
initialPosition := fileStream position.
initialLocalName := self entryBuffer first value.
anEntryWriter := self newEntryWriter.
[ self entryBuffer isEmpty ]
	whileFalse: [ | next entry |
		next := self entryBuffer removeFirst.
		entry := next key.

		"Write entry to file"
		anEntryWriter on: fileStream nextEntryPut: entry ].

"In Linux it was necessary to explicitely flush the file stream"
fileStream flush.
lastStreamPosition := fileStream size ]
	ensure: [ fileStream close ].
self
	refreshEntryPositionsByLocalNameStartingAt: initialPosition
	since: initialLocalName ] in OmBlockFileStore(OmFileStore)>>flushEntryBuffer in Block: [ | initialPosition initialLocalName fileStream |...
[ caught := true.
self wait.
blockValue := mutuallyExcludedBlock value ] in Semaphore>>critical: in Block: [ caught := true....
BlockClosure>>ensure:
Semaphore>>critical:
OmBlockFileStore(OmFileStore)>>critical:
OmBlockFileStore(OmFileStore)>>flushEntryBuffer
OmDeferrer>>sendMessage
[ self sendMessage ] in OmDeferrer>>flush in Block: [ self sendMessage ]
BlockClosure>>ensure:
OmDeferrer>>flush
[ "Loop until enough time passed since last #schedule"
[ DateAndTime now < (lastSchedule + duration) ]
	whileTrue: [ duration wait ].

"Execute deferred action (if not flushed before) and clean up"
self flush ] in OmDeferrer>>runMessageProcess in Block: [ "Loop until enough time passed since last #sched...etc...
[ self value.
Processor terminateActive ] in BlockClosure>>newProcess in Block: [ self value....

```

**Comment by noha** [comment] 2019-10-07 10:00
This doesn‘t look like a problem of OpenAPI. Can you write a mail to the pharo mailing-list? I‘m on vacation and  an look into it in 2 weeks earliest

**Comment by noha** [comment] 2019-10-29 13:28
I cannot reproduce this. Did you figure it out? Can we close this ticket?

**Comment by darth-cheney** [comment] 2019-10-29 13:29
Yeah sorry. According to mailing list this is a known Launcher issue. Feel
free to close.

**Closed as completed** 2019-10-29 13:34 UTC
